version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 10
    reviewers:
      - nhymxu
    assignees:
      - nhymxu
