name: 'Dependency Review'
on: [pull_request]

permission:
  contents: read

jobs:
  dependency-review:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Dependency review
        uses: actions/dependency-review-action@v1
