name: Tests
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ruff lint
        uses: chartboost/ruff-action@v1

  tests:
    # TODO: temporary disable because not log poetry.lock file on repo
    if: ${{ false }}
    needs: linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install library
        run: uv sync --all-extras --all-groups --no-install-project
        working-directory: ${{ github.workspace }}

      - name: Run test
        run: uv run pytest --import-mode=importlib
        working-directory: ${{ github.workspace }}
